"""bagra: incremental bag relational algebra for report subscriptions."""
from .engine import (
    BagraError,
    DuplicateSubscriptionError,
    Engine,
    NegativeMultiplicityError,
    UnknownSubscriptionError,
)
from .interpreter import evaluate
from .plans import (
    And,
    Cmp,
    Not,
    Or,
    Plan,
    distinct,
    except_all,
    filter_,
    intersect_all,
    join,
    plan_from_json,
    pred_from_json,
    project,
    scan,
    union_all,
)

__all__ = [
    "And",
    "BagraError",
    "Cmp",
    "DuplicateSubscriptionError",
    "Engine",
    "NegativeMultiplicityError",
    "Not",
    "Or",
    "Plan",
    "UnknownSubscriptionError",
    "distinct",
    "evaluate",
    "except_all",
    "filter_",
    "intersect_all",
    "join",
    "plan_from_json",
    "pred_from_json",
    "project",
    "scan",
    "union_all",
]
