#!/usr/bin/env python3
"""Usage: patch <source.bin> <patch.json> <out.bin>"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from binpatch.cli import main_patch

if __name__ == "__main__":
    sys.exit(main_patch(sys.argv[1:]))
